TACTIC_NAMES = {
    "TA0003": "Persistence",
    "TA0004": "Privilege Escalation",
    "TA0006": "Credential Access",
    "TA0007": "Discovery",
    "TA0008": "Lateral Movement",
}

LABEL_TO_TECHNIQUE = {
    "dcsync": "T1003.006", "dcsync_convenant": "T1003.006", "dcsync_empire": "T1003.006",
    "mimikatz": "T1003.001",
    "ntds_dump_ninjacopy": "T1003.003", "ntds_dump_ntdsutil": "T1003.003", "ntds_dump_shadowcopy": "T1003.003",
    "kerberos_createnetonly": "T1550.003",
    "pass_the_hash": "T1550.002",
    "password_spraying": "T1110.003",
    "acl_abuse_spn_add": "T1222",
    "acl_abuse_dcsync_right": "T1098",
    "account_creation_admin_group": "T1136.001",
    "dcshadow": "T1207",
    "zerologon": "CVE-2020-1472",
    "nopac_samaccountname_spoofing": "CVE-2021-42287",
    "privexchange": "T1187",
    "bloodhound_enumeration": "T1482",
    "domain_admins_enumeration": "T1069.002",
    "local_group_enumeration": "T1069.001",
    "remote_group_enumeration": "T1069.001",
    "logged_on_users_discovery": "T1033",
    "gpo_modification": "T1484.001",
    "hidden_account_creation": "T1136.001",
    "rid_hijacking": "T1098",
    "sid_history_injection": "T1134.005",
    "machine_account_hash_change": "T1098",
    "local_admin_password_changed": "T1098",
    "privileged_group_membership_abuse": "T1098",
    "psexec_lateral_movement": "T1021.002",
    "psexec_like_lateral_movement": "T1021.002",
    "remote_service_lateral_movement": "T1021.002",
    "scheduled_task_lateral_movement": "T1053.005",
    "winrm_lateral_movement": "T1021.006",
    "wmi_lateral_movement": "T1047",
    "dsrm_password_change": "T1098",
    "post_zerologon_password_reset": "T1098",
}

LABEL_DESCRIPTIONS = {
    "dcsync": "Replication DCSync: extraction of password hashes via the AD replication protocol",
    "dcsync_convenant": "DCSync executed through the Covenant C2 framework",
    "dcsync_empire": "DCSync executed through the Empire C2 framework",
    "mimikatz": "In-memory credential extraction via Mimikatz (LSASS)",
    "ntds_dump_ninjacopy": "NTDS.dit extraction via NinjaCopy",
    "ntds_dump_ntdsutil": "NTDS.dit extraction via ntdsutil",
    "ntds_dump_shadowcopy": "NTDS.dit extraction via Volume Shadow Copy",
    "kerberos_createnetonly": "Sacrificial Kerberos session (Rubeus createnetonly), often a precursor to Pass-the-Ticket",
    "pass_the_hash": "Authentication using a stolen NTLM hash (Pass-the-Hash)",
    "password_spraying": "Low-and-slow authentication attempts against many accounts to avoid lockouts",
    "acl_abuse_spn_add": "Abuse of AD ACL rights to add a Service Principal Name for Kerberoasting",
    "acl_abuse_dcsync_right": "Abuse of AD ACL rights to grant DCSync replication permissions",
    "account_creation_admin_group": "Creation of an account and addition to a privileged group",
    "dcshadow": "Rogue domain controller registration to push unauthorized directory changes",
    "zerologon": "Exploitation of CVE-2020-1472 to reset the domain controller machine account password",
    "nopac_samaccountname_spoofing": "Exploitation of CVE-2021-42287/42278 via SAM account name spoofing",
    "privexchange": "Abuse of Exchange privileges to escalate to Domain Admin",
    "bloodhound_enumeration": "AD relationship enumeration via BloodHound for attack path discovery",
    "domain_admins_enumeration": "Enumeration of the Domain Admins group membership",
    "local_group_enumeration": "Enumeration of local group membership",
    "remote_group_enumeration": "Remote enumeration of group membership",
    "logged_on_users_discovery": "Discovery of currently logged-on users on a host",
    "gpo_modification": "Modification of a Group Policy Object",
    "hidden_account_creation": "Creation of a hidden local account",
    "rid_hijacking": "RID hijacking to grant administrative privileges to a low-privilege account",
    "sid_history_injection": "Injection of a privileged SID into the SID history attribute",
    "machine_account_hash_change": "Unexpected machine account password/hash change",
    "local_admin_password_changed": "Local administrator password change",
    "privileged_group_membership_abuse": "Unauthorized addition of an account to a privileged group",
    "psexec_lateral_movement": "Lateral movement via PsExec-style remote service execution",
    "psexec_like_lateral_movement": "Lateral movement via a PsExec-like remote execution tool",
    "remote_service_lateral_movement": "Lateral movement via remote service creation",
    "scheduled_task_lateral_movement": "Lateral movement via remote scheduled task creation",
    "winrm_lateral_movement": "Lateral movement via WinRM/PowerShell remoting",
    "wmi_lateral_movement": "Lateral movement via WMI remote execution",
    "dsrm_password_change": "Directory Services Restore Mode password change",
    "post_zerologon_password_reset": "Password reset performed following a Zerologon exploitation",
    "benign": "Normal authentication or directory activity consistent with baseline behavior",
}

ACTIONS = {
    "pass_the_hash": ["Reset credentials for the affected account", "Review logons from the source workstation (last 24h)", "Check for lateral connections to other hosts"],
    "mimikatz": ["Isolate the affected host from the network", "Rotate credentials for all recent logons on the host", "Capture a memory image before remediation"],
    "dcsync_empire": ["Audit DS-Replication-Get-Changes grantees", "Reset the KRBTGT password (twice, 24h apart)", "Review Empire C2 indicators across the domain"],
    "dcsync_convenant": ["Reset the KRBTGT password (twice, 24h apart)", "Audit replication permissions domain-wide", "Hunt for Covenant C2 beacon patterns"],
    "dcsync": ["Audit DS-Replication-Get-Changes grantees", "Reset the KRBTGT password (twice, 24h apart)"],
    "kerberos_createnetonly": ["Correlate the logon ID across subsequent events", "Check for Rubeus artifacts on the source host", "Flag the ticket for Pass-the-Ticket follow-up"],
    "ntds_dump_shadowcopy": ["Escalate to full incident response", "Isolate the domain controller immediately", "Begin domain-wide credential rotation"],
    "ntds_dump_ninjacopy": ["Escalate to full incident response", "Isolate the domain controller immediately", "Begin domain-wide credential rotation"],
    "ntds_dump_ntdsutil": ["Escalate to full incident response", "Isolate the domain controller immediately", "Begin domain-wide credential rotation"],
    "zerologon": ["Patch CVE-2020-1472 immediately", "Reset the domain controller machine account password", "Audit for follow-on DCSync activity"],
    "nopac_samaccountname_spoofing": ["Patch CVE-2021-42287/42278", "Audit recently created machine accounts", "Review Domain Admin group membership"],
    "dcshadow": ["Identify and remove the rogue DC registration", "Audit recent directory replication changes", "Reset KRBTGT twice"],
    "bloodhound_enumeration": ["Identify the source workstation and account", "Review recent LDAP query volume from that host", "Audit exposed attack paths to Domain Admins"],
    "domain_admins_enumeration": ["Correlate with subsequent privilege escalation attempts", "Review source account's recent activity"],
    "password_spraying": ["Identify targeted accounts and lock down if needed", "Enable/verify account lockout policies", "Check source IP against threat intel"],
    "account_creation_admin_group": ["Verify the account creation was authorized", "Review who performed the group addition", "Disable the account if unauthorized"],
    "gpo_modification": ["Review the GPO change history", "Verify the modifying account's authorization", "Roll back if unauthorized"],
    "scheduled_task_lateral_movement": ["Review the scheduled task definition on the target host", "Correlate with the source account's other activity"],
    "wmi_lateral_movement": ["Review WMI event consumers on the target host", "Correlate with the source account's other activity"],
    "winrm_lateral_movement": ["Review PowerShell remoting logs on the target host", "Correlate with the source account's other activity"],
    "psexec_lateral_movement": ["Review the remote service created on the target host", "Correlate with the source account's other activity"],
    "psexec_like_lateral_movement": ["Review the remote service created on the target host", "Correlate with the source account's other activity"],
    "benign": [],
}


def enrich_prediction(prediction: dict) -> dict:
    label = prediction.get("predicted_label")
    prediction["predicted_technique"] = LABEL_TO_TECHNIQUE.get(label)
    prediction["tactic_name"] = TACTIC_NAMES.get(prediction.get("predicted_tactic"))
    fallback = (label or "").replace("_", " ").capitalize() if label else "Unknown technique"
    prediction["description"] = LABEL_DESCRIPTIONS.get(label, fallback)
    return prediction
