credential_access:
  - file: "CA_DCSync_4662.evtx"
    label: "dcsync"
    tactic: "TA0006"
    technique: "T1003.006"
  - file: "kerberos_pwd_spray_4771.evtx"
    label: "password_spraying"
    tactic: "TA0006"
    technique: "T1110.003"
  - file: "ACL_ForcePwd_SPNAdd_User_Computer_Accounts.evtx"
    label: "acl_abuse_spn_add"
    tactic: "TA0006"
    technique: "T1222"
  - file: "4794_DSRM_password_change_t1098.evtx"
    label: "dsrm_password_change"
    tactic: "TA0003"
    technique: "T1098"
  - file: "remote_pwd_reset_rpc_mimikatz_postzerologon_target_DC.evtx"
    label: "post_zerologon_password_reset"
    tactic: "TA0004"
    technique: "T1098"
  - file: "Zerologon_VoidSec_CVE-2020-1472_4626_LT3_Anonym_follwedby_4742_DC_Anony_DC.evtx"
    label: "zerologon"
    tactic: "TA0004"
    technique: "CVE-2020-1472"
  - file: "Sysmon13_MachineAccount_Password_Hash_Changed_via_LsarSetSecret.evtx"
    label: "machine_account_hash_change"
    tactic: "TA0006"
    technique: "T1098"
  - file: "Sysmon_13_Local_Admin_Password_Changed.evtx"
    label: "local_admin_password_changed"
    tactic: "TA0003"
    technique: "T1098"

discovery:
  - file: "dicovery_4661_net_group_domain_admins_target.evtx"
    label: "domain_admins_enumeration"
    tactic: "TA0007"
    technique: "T1069.002"
  - file: "discovery_bloodhound.evtx"
    label: "bloodhound_enumeration"
    tactic: "TA0007"
    technique: "T1482"
  - file: "discovery_local_user_or_group_windows_security_4799_4798.evtx"
    label: "local_group_enumeration"
    tactic: "TA0007"
    technique: "T1069.001"
  - file: "4799_remote_local_groups_enumeration.evtx"
    label: "remote_group_enumeration"
    tactic: "TA0007"
    technique: "T1069.001"
  - file: "discovery_psloggedon.evtx"
    label: "logged_on_users_discovery"
    tactic: "TA0007"
    technique: "T1033"

lateral_movement:
  - file: "LM_4624_mimikatz_sekurlsa_pth_source_machine.evtx"
    label: "pass_the_hash"
    tactic: "TA0008"
    technique: "T1550.002"
  - file: "ImpersonateUser-via local Pass The Hash Sysmon and Security.evtx"
    label: "pass_the_hash"
    tactic: "TA0008"
    technique: "T1550.002"
  - file: "LM_WMI_4624_4688_TargetHost.evtx"
    label: "wmi_lateral_movement"
    tactic: "TA0008"
    technique: "T1047"
  - file: "remote task update 4624 4702 same logonid.evtx"
    label: "scheduled_task_lateral_movement"
    tactic: "TA0008"
    technique: "T1053.005"
  - file: "LM_PowershellRemoting_sysmon_1_wsmprovhost.evtx"
    label: "winrm_lateral_movement"
    tactic: "TA0008"
    technique: "T1021.006"
  - file: "LM_winrm_target_wrmlogs_91_wsmanShellStarted_poorLog.evtx"
    label: "winrm_lateral_movement"
    tactic: "TA0008"
    technique: "T1021.006"
  - file: "LM_ScheduledTask_ATSVC_target_host.evtx"
    label: "scheduled_task_lateral_movement"
    tactic: "TA0008"
    technique: "T1053.002"
  - file: "LM_Remote_Service01_5145_svcctl.evtx"
    label: "remote_service_lateral_movement"
    tactic: "TA0008"
    technique: "T1021.002"
  - file: "LM_REMCOM_5145_TargetHost.evtx"
    label: "psexec_like_lateral_movement"
    tactic: "TA0008"
    technique: "T1021.002"
  - file: "lm_sysmon_psexec_smb_meterpreter.evtx"
    label: "psexec_lateral_movement"
    tactic: "TA0008"
    technique: "T1021.002"

persistence:
  - file: "Network_Service_Guest_added_to_admins_4732.evtx"
    label: "privileged_group_membership_abuse"
    tactic: "TA0003"
    technique: "T1098"
  - file: "DACL_DCSync_Right_Powerview_ Add-DomainObjectAcl.evtx"
    label: "acl_abuse_dcsync_right"
    tactic: "TA0003"
    technique: "T1098"
  - file: "persistence_security_dcshadow_4742.evtx"
    label: "dcshadow"
    tactic: "TA0003"
    technique: "T1207"
  - file: "persistence_hidden_local_account_sysmon.evtx"
    label: "hidden_account_creation"
    tactic: "TA0003"
    technique: "T1136.001"
  - file: "persist_valid_account_guest_rid_hijack.evtx"
    label: "rid_hijacking"
    tactic: "TA0003"
    technique: "T1098"
  - file: "sysmon_local_account_creation_and_added_admingroup_12_13.evtx"
    label: "account_creation_admin_group"
    tactic: "TA0003"
    technique: "T1136.001"
  - file: "persistence_pendingGPO_sysmon_13.evtx"
    label: "gpo_modification"
    tactic: "TA0003"
    technique: "T1484.001"

privilege_escalation:
  - file: "4765_sidhistory_add_t1178.evtx"
    label: "sid_history_injection"
    tactic: "TA0004"
    technique: "T1134.005"
  - file: "samaccount_spoofing_CVE-2021-42287_CVE-2021-42278_DC_securitylogs.evtx"
    label: "nopac_samaccountname_spoofing"
    tactic: "TA0004"
    technique: "CVE-2021-42287"
  - file: "privexchange_dirkjan.evtx"
    label: "privexchange"
    tactic: "TA0004"
    technique: "T1187"
